name: Ping All

# workflow_dispatch: Enables using this GH Action as an REST API/Webhook
on: workflow_dispatch

jobs:
  ping-inventory:
    # All self-hosted runners in Route Views GH Org are withinin RV subnet (128.223.51.0/24) 
    # ==> So, self-hoster runners have ACL-based access to all RV inventory 
    runs-on: self-hosted 
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
        working-directory: ansible

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install pinned dependencies
        run: |
          pip install -r requirements.txt

      - name: Run ping playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbooks/ping.yml
          directory: ansible
          # SSH private key
          key: ${{secrets.ROOT_SSH_KEY_RSA}}
          # SSH known hosts file content (Optional)
          # known_hosts: .known_hosts
          # encrypted vault password  (Optional)
          # vault_password: ${{secrets.ANSIBLE_VAULT_PASS}}
          # galaxy requirements filepath  (Optional)
          # requirements: galaxy-requirements.yml
          # additional flags to pass to ansible-playbook (Optional)
          options: |
            --user root
